version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  django:
    build: ./backend/ecommerce_backend/
    volumes:
      - ./backend/ecommerce_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - zookeeper
    env_file:
      - backend/ecommerce_backend/.env  # Path to your .env file

