# Generated by Django 5.0 on 2023-12-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Ordered", "Ordered"),
                    ("Abandoned", "Abandoned"),
                ],
                default="Open",
                max_length=10,
            ),
        ),
    ]
