# Generated by Django 5.0 on 2023-12-23 17:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
